### ISSUE TITLE
Duplicate items

### ISSUE THREAD

**Issue by ghost** [akump/realtime-coinbase-wallet#1] opened 2021-11-23 14:15 UTC
On macOS Monterey after adding the api info it starts generating duplicate entires for all coins in your wallet. It is almost like every refresh just adds a whole new set of items instead of updating the already existing lines. 
<img width="283" alt="Screen Shot 2021-11-23 at 9 15 31 AM" src="https://user-images.githubusercontent.com/90982783/143040356-7399319c-1f17-4ff1-b998-f240dac8757a.png">

**Comment by akump** [comment] 2021-11-23 17:47
Ok I'll see what I can do

**Comment by akump** [comment] 2021-11-23 18:25
@Gurky-Kronos There's a new release, 1.0.1, here: https://github.com/akump/realtime-coinbase-wallet/releases/tag/1.0.1. This _might_ fix it. I'm currently not able to reproduce, but I've read through the code and determined a potential cause. If you're tech savvy, you can clone this repo, install electron, and run `electron .` from the root of the dir. If you have vs code, you can also run `electron .` from a debug terminal and step through line by line and see the bug. It'd be in this function most likely: https://github.com/akump/realtime-coinbase-wallet/blob/1.0.1/index.js#L87

**Comment by ghost** [comment] 2021-11-23 19:18
@akump looks like that did the trick!

**Comment by akump** [comment] 2021-11-23 19:26
Sweet! I'll close the issue.

**Closed as completed by akump** 2021-11-23 19:26 UTC
